server:
  port: 8080

spring:
  application:
    name: iot-device-service
  kafka:
    # For Docker: use kafka:29092
    # For local development: use localhost:9094
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

iot:
  kafka:
    topic: iot-logs
