spring:
  application:
    name: backend-service
  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:localhost}
    port: ${SPRING_CASSANDRA_PORT:9042}
    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE_NAME:hivemind}
    local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER:datacenter1}
    schema-action: create-if-not-exists

server:
  port: 8080

logging:
  level:
    com.security.backend: INFO
    org.springframework.data.cassandra: DEBUG
